### ISSUE TITLE
Sync product deletions

### ISSUE THREAD

**Issue by philippdaun** [lucasvocos/gatsby-sanity-shopify#1]
First off, thanks for making this! I hadn't even thought of syncing Shopify products with a 3rd-party CMS.

Am I correct in assuming that the lambda function currently handles product creation and update, but doesn't deal with product deletions? That'd be great to have, even if behind a flag. I guess there's no harm in deleting datasets though if the source of truth is Shopify's database.

**Comment by lucasvocos** [comment]
@philippdaun great idea! 

Correct, the lambda function comes from Kevin Green (https://github.com/iamkevingreen) and I just put this pack together to boilerplate some upcoming projects for myself. So far it creates products (and corresponding variants) on new products and updates existing ones.

However, I think that's a great idea. I'll start working on something, maybe add both a way to delete or make some kind of flagging system

**Comment by iamkevingreen** [comment]
@philippdaun So the reason I don't do this, is for a similar reason that Sanity doesn't yet have bulk edit. The reason is if you have products associated anywhere in the schema to other objects (think related products, featured products on other pages etc) suddenly having that removed automatically because someone in shopify deleted a product doesn't sound like a good time :). 

Additionally the build might break if a product suddenly wasn't available. So I would trend carefully with the deleting. I actually choose to hold the sanity keys for product delete so that the client can't break anything, but that's because my current project has so much nesting that it would be a big headache to suddenly have a product go poof.

**Comment by lucasvocos** [comment]
@iamkevingreen gotcha, that's really helpful insight! 

For now I've included a way to set a `deleted` boolean to true or false and included a note that this might be helpful to query for in the front end. Like, only render products where `deleted === false` or something.

@philippdaun the change can be found here: https://github.com/lucasvocos/gatsby-sanity-shopify/pull/2

**Comment by philippdaun** [comment]
@iamkevingreen That's good input indeed. Most backends I know handle this with soft deletes — missing data is going to be a headache in any case, but this limits it to the output layer and allows automated filtering instead of nasty exceptions. I like your solution, @lucasvocos!
